name: creamy_field
description: A Text Editing Field with rich text & syntax highlight support.
version: 0.1.0
homepage: https://github.com/predatorx7/snake_code/tree/master/packages/rich_code_editor

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.6.0
  highlight: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
