name: creamy_field
description: Rich Text Editing Field & other components with rich text, selection toolbar & syntax highlight support. Useful in Rich text editors.
version: 0.3.3+1
homepage: https://github.com/predatorx7/snake_code/tree/packages/creamy_field/packages/creamy_field

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ^1.22.0

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.6.0
  highlight: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter