name: creamy_field
description: A Text Editing Field with rich text & syntax highlight support. Useful in Rich text editors.
version: 0.2.3
homepage: https://github.com/predatorx7/snake_code/tree/master/packages/creamy_field

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.6.0
  highlight: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
